services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel-api
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network

    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: bruning_db
            MYSQL_USER: bruning
            MYSQL_PASSWORD: bruning_password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network

volumes:
    mysql_data:
        driver: local

networks:
    laravel_network:
        driver: bridge
